apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim # pvc 이름
spec:
  storageClassName: mariadb-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi