apiVersion: v1
kind: Pod
metadata:
  name: frontend1
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: my-custom-nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
