FROM ubuntu:22.04
# RUN mkdir /home/dev_workflow
# WORKDIR /home/dev_workflow
# ADD ./requirements.txt /home/dev_workflow/requirements.txt
RUN apt-get update && apt-get install -y sudo
RUN apt-get install -y git
RUN apt-get -y install python3
RUN apt-get -y install python3-pip