apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-volume # pv 이름
  labels:
    type: local
spec:
  storageClassName: mariadb-storage-class
  capacity:
    storage: 1Gi # 스토리지 용량 크기
  accessModes:
    - ReadWriteOnce # 하나의 Pod에서만 access가 가능하도록 설정, ReadWriteMany는 여러 개 노드에서 접근 가능
  hostPath:
    path: "/data/mariadb" # node에 저장될 스토리지 공간
    # path: "/data/k8s/db/" # node에 저장될 스토리지 공간