apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-files-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sftp-ssh-service
spec:
  selector:
    app: nginx-phpfpm
  type: NodePort
  ports:
    - name: sftp
      protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30222
    - name: ssh
      protocol: TCP
      port: 2222
      targetPort: 2222
      nodePort: 30223
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-phpfpm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-phpfpm
  template:
    metadata:
      labels:
        app: nginx-phpfpm
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: shared-files-pvc
        - name: nginx-config-volume
          configMap:
            name: nginx-config

      initContainers:
        - name: init-home-dirs
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p /mnt/user1 /mnt/pondol && \
              chown 1001:1001 /mnt/user1 && \
              chown 1002:1002 /mnt/pondol
          volumeMounts:
            - name: shared-files
              mountPath: /mnt

      containers:
        - name: phpfpm82
          image: php-8-2-fpm:1.0.0
          imagePullPolicy: Never
          volumeMounts:
            - name: shared-files
              mountPath: /home  # 필요 시 변경 가능

        - name: nginx
          image: nginx:1.27.5
          volumeMounts:
            - name: shared-files
              mountPath: /home
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d

        - name: sftp
          image: atmoz/sftp:latest
          ports:
            - containerPort: 22
              name: sftp
          volumeMounts:
            - name: shared-files
              mountPath: /home/user1
              subPath: user1
            - name: shared-files
              mountPath: /home/pondol
              subPath: pondol
          args:
            - "user1:password1:1001::/home/user1"
            - "pondol:password2:1002::/home/pondol"

        - name: ssh
          image: ssh-multiuser:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 2222
              name: ssh
          volumeMounts:
            - name: shared-files
              mountPath: /home/user1
              subPath: user1
            - name: shared-files
              mountPath: /home/pondol
              subPath: pondol
