apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-files-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sftp-ssh-service
spec:
  selector:
    app: nginx-phpfpm
  type: NodePort
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30222
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-phpfpm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-phpfpm
  template:
    metadata:
      labels:
        app: nginx-phpfpm
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 0
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: shared-files-pvc
        - name: nginx-main-config
          configMap:
            name: nginx-main-config
        - name: nginx-config-volume
          configMap:
            name: nginx-config
      containers:
        - name: nginx
          image: nginx:1.27.5
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: shared-files
              mountPath: /home
            - name: nginx-main-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d

        - name: ssh
          image: pondol/ssh-sftp-custom:latest
          ports:
            - containerPort: 22
              name: ssh
          volumeMounts:
            - name: shared-files
              mountPath: /home
        - name: phpfpm82
          image: php-8-2-fpm:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: shared-files
              mountPath: /home
